apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-3bk3
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0022-tenant/tkrw-pr712-0075-0022-app/devfile-sample-3bk3@sha256:80f979855da5b4b4579db55c170e88f9bfcf59040a14c393945420e3de1d27fc
        name: my-nodejs
        resources: {}
status: {}
